# Generated by Django 2.1.7 on 2024-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_img', models.FileField(upload_to='static\\ProductImages')),
                ('upload_time', models.DateTimeField()),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(default='Available', max_length=100)),
            ],
            options={
                'db_table': 'UploadProductModel',
            },
        ),
    ]
