# Generated by Django 5.0.6 on 2024-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploadproductmodel_id_alter_usersmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remail', models.EmailField(max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('chat', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ChatModel',
            },
        ),
    ]
