# Generated by Django 5.0.6 on 2024-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
