# Generated by Django 5.0.6 on 2024-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatmodel_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_img', models.FileField(upload_to='static\\ProductImages')),
                ('upload_time', models.DateTimeField()),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('collectedemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'CollectedProducts',
            },
        ),
    ]
