# Generated by Django 5.0.6 on 2024-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_collectedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
